### ISSUE TITLE
Face culling is off

### ISSUE THREAD

**Issue by jena-s-lab** [faceofcat/BC-Ore-Processing#10]
![2018-01-15_21 34 18](https://user-images.githubusercontent.com/625236/34960857-02017cb4-fa3d-11e7-94e7-97070495b19f.png)
Can you try to implement the method `shouldSideBeRendered`:
```kotlin
    fun shouldSideBeRendered() {
         return true;
    }
```
Sorry, I have no time to re-deploy the dev env. 🙁

**Comment by jena-th** [comment]
may solve #7
