### ISSUE TITLE
some suggestions

### ISSUE THREAD

**Issue by 0Navis0** [faceofcat/BC-Ore-Processing#11]
Ore and Fluid processor, as sender and receiver pipes should display in buildcraft guide book. They should have a gui as other Buildcraft machines.

**Comment by BigCasper** [comment]
I have to disagree on the GUI: Quarry never had one, as well as GUI's being overdone in the modding community. That's the reason I like the mod so much, no boring GUI's, as simple as it gets, but so much possibility!
