### ISSUE TITLE
Recipe tampering?

### ISSUE THREAD

**Issue by BigCasper** [faceofcat/BC-Ore-Processing#14]
I'm making a pack, and I really wanted to have ingot re-smelting as well as some ores removed. Some basic config tinkering later, I've figured out how to add some basic smelting and solidifying recipes. Could you advise how to proceed with this rather unintuitive process? Especially how not to have 20 different ingot smelting recipes in the config, but rather one patter for your brilliant code machine to recognize?

**Comment by faceofcat** [comment]
I really doubt it knows how to handle any patterns... :(

but that's a cool thing to add... :)... wish I had the time...

**Comment by BigCasper** [comment]
I've stiched up something like this, only removal of some recipes without removing the liquid (cuz you can just delete a liquid from the liquid base JSON) would be needed:
{
    "input_stack": { "ore": "ingotIron" },
    "ticks": 240,
    "output_fluids": {
      "first": { "name": "bcop-iron-searing", "quantity": 333 },
      "second": { "name": "bcop-gaseous_lava-searing", "quantity": 5 }
    }
  },
  {
    "input_stack": { "ore": "ingotGold" },
    "ticks": 240,
    "output_fluids": {
      "first": { "name": "bcop-gold-searing", "quantity": 333 },
      "second": { "name": "bcop-gaseous_lava-searing", "quantity": 5 }
    }
  },
  {
    "input_stack": { "ore": "ingotSilver" },
    "ticks": 240,
    "output_fluids": {
      "first": { "name": "bcop-silver-searing", "quantity": 333 },
      "second": { "name": "bcop-gaseous_lava-searing", "quantity": 5 }
    }
  },
  {
    "input_stack": { "ore": "ingotTin" },
    "ticks": 240,
    "output_fluids": {
      "first": { "name": "bcop-tin-searing", "quantity": 333 },
      "second": { "name": "bcop-gaseous_lava-searing", "quantity": 5 }
    }
  },
  {
    "input_stack": { "ore": "ingotCopper" },
    "ticks": 240,
    "output_fluids": {
      "first": { "name": "bcop-copper-searing", "quantity": 333 },
      "second": { "name": "bcop-gaseous_lava-searing", "quantity": 5 }
    }
  },
  {
    "input_stack": { "ore": "ingotNickel" },
    "ticks": 240,
    "output_fluids": {
      "first": { "name": "bcop-nickel-searing", "quantity": 333 },
      "second": { "name": "bcop-gaseous_lava-searing", "quantity": 5 }
    }
  },
  {
    "input_stack": { "ore": "ingotPlatinum" },
    "ticks": 240,
    "output_fluids": {
      "first": { "name": "bcop-platinum-searing", "quantity": 333 },
      "second": { "name": "bcop-gaseous_lava-searing", "quantity": 5 }
    }
  },
  {
    "input_stack": { "ore": "ingotTitanium" },
    "ticks": 240,
    "output_fluids": {
      "first": { "name": "bcop-titanium-searing", "quantity": 333 },
      "second": { "name": "bcop-gaseous_lava-searing", "quantity": 5 }
    }
  },
  {
    "input_stack": { "ore": "ingotZinc" },
    "ticks": 240,
    "output_fluids": {
      "first": { "name": "bcop-zinc-searing", "quantity": 333 },
      "second": { "name": "bcop-gaseous_lava-searing", "quantity": 5 }
    }
  },
  {
    "input_stack": { "ore": "ingotTin" },
    "ticks": 240,
    "output_fluids": {
      "first": { "name": "bcop-tin-searing", "quantity": 333 },
      "second": { "name": "bcop-gaseous_lava-searing", "quantity": 5 }
    }
  }
