### ISSUE TITLE
Custom Liquids?

### ISSUE THREAD

**Issue by BigCasper** [faceofcat/BC-Ore-Processing#15]
I've seen that your mod takes it's liquids from JSONs. Is it possible to add some custom liquids in those? If so, how? I've tried a couple of ways and those ain't working...

**Comment by faceofcat** [comment]
you can surely add custom liquids... but only custom EXISTING liquids... :)

you can't use this mod to register new types of fluids.

**Comment by BigCasper** [comment]
@faceofcat  doesn't the mod build it's liquids from like "fluid-base.json"?

**Comment by BigCasper** [comment]
@faceofcat wouldn't modifying fluid-base.json of this mod allow for registration of custom fluids? since if you remove an entry, that fluid disappears I thought it would work the other way around...

**Comment by faceofcat** [comment]
it would... but I think there are some "quirks" around it...

**Comment by faceofcat** [comment]
it has to also have valid ore/ingots for said fluid:

https://github.com/MinecraftModDevelopmentMods/BC-Ore-Processing/blob/1.12/src/main/kotlin/net/ndrei/bcoreprocessing/lib/fluids/FluidsRegistry.kt#L60-L71

**Comment by BigCasper** [comment]
> it would... but I think there are some "quirks" around it...

So... How to do that?
Since I wanted to have an alloy in this form, I don't have any ores for that...
I could use an unused dummy ore that just doesn't generate for a different material... or add an oredictionary entry for it in the apropriate format...

**Comment by faceofcat** [comment]
well... the way these machines work... they start with an ore -> fluid (different temperatures) -> ingots... right?

so you do have to have an ore and an ingot for every fluid...

when it comes to alloys... maybe adding a new machine that does alloys starting with 2 fluids... :)... that's an idea.

**Comment by BigCasper** [comment]
> well... the way these machines work... they start with an ore -> fluid (different temperatures) -> ingots... right?
> 
> so you do have to have an ore and an ingot for every fluid...
> 
> when it comes to alloys... maybe adding a new machine that does alloys starting with 2 fluids... :)... that's an idea.

I mean I have the means to MAKE the alloy liquid, I just need the alloy liquid registered with those temperature variations

**Comment by BigCasper** [comment]
> well... the way these machines work... they start with an ore -> fluid (different temperatures) -> ingots... right?
> 
> so you do have to have an ore and an ingot for every fluid...
> 
> when it comes to alloys... maybe adding a new machine that does alloys starting with 2 fluids... :)... that's an idea.

Got it! I forced the mod to make me a custom fluid! You need literally any item with an "ingot[material]" oredict, and any item with a "ore[material]" oredict. Materials ingot-ore can be different. Then plug it into the pattern for iron/gold in the fluid-base.json. Closing!
