### ISSUE TITLE
Server crash 1.11.2

### ISSUE THREAD

**Issue by SFort** [faceofcat/BC-Ore-Processing#5]
[crash-2017-10-12_15.34.48-server](https://github.com/faceofcat/BC-Ore-Processing/files/1379476/crash-2017-10-12_15.34.48-server.txt)

forge:1.11.2-13.20.1.2510
bc-ore-processing: 1.11.2-1-HF

**Comment by faceofcat** [comment]
that's bad... will get it fixed ASAP!

**Comment by faceofcat** [comment]
new version should be available here: [BC-Ore-Processing - 1.11.2 - 2](https://minecraft.curseforge.com/projects/bc-ore-processing/files/2490098)
as soon as it gets approved by curse.
