### ISSUE TITLE
Ore processing of Forestry Tin

### ISSUE THREAD

**Issue by Gragnar** [faceofcat/BC-Ore-Processing#8]
This setup has worked with iron, gold and forestry copper but the fluid processor won't output tin ingots.
![image](https://user-images.githubusercontent.com/7951011/34912063-86696f06-f8a4-11e7-9ee1-e27bdb2afc0c.png)

**Comment by Gragnar** [comment]
Other part of the setup in case it helps. The liquid in the fluid processor is the cooled version. 
![image](https://user-images.githubusercontent.com/7951011/34912122-857b6264-f8a6-11e7-880b-c74ff001b2fc.png)

**Comment by Gragnar** [comment]
Mod list:

[1.12]MoVillages-1.5.4
aether_legacy-1.12.2-v1.0.1
ancientwarfare-1.12.2-2.4.37
AppleSkin-mc1.12-1.0.9
Aroma1997Core-1.12.2-1.3.0.2
AromaBackup-1.12.2-2.1.1.3
ATLCraftCandlesMod(MC1.12-Ver1.9)
AutoRegLib-1.3-15
backpacks 1.12.2 - 3.4.2
bc-extra-pipes-7.99.13-1
bc-ore-processing-7.99.13-1
BetterBedrockGenerator-1.12-6.1.1
BiblioCraft[v2.4.3][MC1.12.0]
binnie-mods-1.12.2-2.5.0.111
Biome_Bundle-1.12.2-v6.1
buildcraft-7.99.13
CarryOn MC1.12 v1.7
Chameleon-1.12-4.1.3
ChestTransporter-1.12-2.8.7
ChickenChunks-1.12.2-2.4.1.71-universal
Chisel-MC1.12-0.1.1.24
chiselsandbits-14.11
CleanView-1.12.2-v1
CodeChickenLib-1.12.2-3.1.5.331-universal
ColoredWater-1.12.2-b34
colytra-1.12.2-1.0.4.3
CookingForBlockheads_1.12.1-6.3.17
corail_pillar_extension_chisel-4.0.0-1.12
corail_pillar_extension_forestry-4.0.0-1.12
corail_pillar_extension_quark-4.0.0-1.12
corail_pillar-4.0.0-1.12
CTD-Core-1.12.2-1.2.2
CTM-MC1.12-0.2.3.9
CustomNPCs_1.12.2(29oct17)
Decocraft-2.5.2_1.12.2
diethopper-1.1
dirt2path-1.7.0
Duckcraft-1.12.2-3.0.7
DynamicSurroundings-1.12.2-3.4.7.2
EnchantingTable-1.12-1.1.2
fairylights-2.1.2-1.12.x
FarmingForBlockheads_1.12-3.1.5
fencejumper-1.12-1.0.1
flatcoloredblocks-mc1.12-6.6
forestry_1.12.2-5.7.0.231
Forgelin-1.6.0
gravestone-1.10.0
InventoryTweaks-1.63
IvToolkit-1.3.3-1.12
jei_1.12.2-4.8.5.138
jeibees-0.9.0.5-mc1.12.2
journeymap-1.12.2-5.5.2
JustEnoughResources-1.12.2-0.8.5.27
KleeSlabs_1.12-5.3.2
malisiscore-1.12.2-6.3.0
malisisdoors-1.12.2-7.2.2
MCA-1.12.x-5.3.1-universal
mcjtylib-1.12-2.6.1
meecreeps-1.12-1.1.0
missing_pieces-1.12.2-4.3.0
MobGrindingUtils-0.3.4
Mo-Glowstone-1.12.2-1.4.4
moreoverlays-1.13-mc1.12.1
MouseTweaks-2.8-mc1.12.1
NetherPortalFix_1.12.1-5.3.13
NoFov-MC1.12-1.0.1
NoNausea-MC1.12-1.0
notenoughwands-1.12-1.6.0
OpenTerrainGenerator-1.12.2 - v4
OptiFine_1.12.2_HD_U_C7
OTG-Core
Pam's HarvestCraft 1.12.2b - Re-Balance Update
Placebo-1.12.2-1.1.3
Quark-r1.4-120
QuickLeafDecay-MC1.12.1-1.2.4
RadixCore-1.12.x-2.2.1-universal
RecurrentComplex-1.4.6
redstonepaste-mc1.12-1.7.5
roost-1.12-1.2.0
rustic-0.4.5
signpost-1.12-1.05.5
SimpleGrinder-4.110.R1122
simplemagnet-1.12.2-1.2.9
stacksize-1.12.2-1.0
StorageDrawers-1.12.1-5.3.3
StorageDrawersExtras-1.12-3.1.0
theoneprobe-1.12-1.4.19
torchmaster_1.12.2-1.6.1.53
twilightforest-1.12.2-3.5.263-universal
UnlimitedChiselWorks-0.1.9
Vanilla Builders Extension-1.12-1.0.6
VeinMiner-1.12-0.38.1.639+134fb1e
Waddles-1.12.2-0.5.6
Wither Skeleton Tweaks-1.12.2-2.3.0

**Comment by Ghent** [comment]
It should accept Forestry tin.  I'm using it right now and it seems fine.
